declare module '*.pages.yaml' {}
declare module '*.pages.yml' {}
declare module '*.pages.json' {}
declare module '*.pages.ts' {}
declare module '*.pages.tsx' {}
declare module '*.pages.cts' {}
declare module '*.pages.mts' {}
declare module '*.pages.ctsx' {}
declare module '*.pages.mtsx' {}
declare module '*.pages.js' {}
declare module '*.pages.cjs' {}
declare module '*.pages.mjs' {}
declare module '*.pages.jsx' {}
declare module '*.pages.cjsx' {}
declare module '*.pages.mjsx' {}
