on:
  push:
    branches: master

name: Publish to NPM

jobs:
  test:
    runs-on:
      - veritas
      - linux
      - arm64
    container: grexie/node-docker:lts
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json', 'yarn.lock') }}
      - if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - run: yarn build
      - name: test
        run: yarn test

  publish:
    name: publish
    needs: test
    runs-on:
      - veritas
      - linux
      - arm64
    container: grexie/node-docker:lts
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ matrix.node-version }}--${{ runner.OS }}-build-${{ hashFiles('package.json', 'yarn.lock') }}
      - if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - run: yarn build
      - run: npm run release patch --github.release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
